import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { specialGothic } from './fonts';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Audio Alchemic",
  description: "Generated by create next app",
  icons:{
    icon:['/favicon_io/favicon_io.ico'],
    apple:['/favicon_io/apple-touch-icon.png'],
    shortcut:['/favicon_io/apple-touch-icon.png']
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${specialGothic.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
