import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { specialGothic } from "./fonts"; // your custom font import

export const metadata: Metadata = {
  title: "Audio Alchemic",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon_io/favicon_io.ico"],
    apple: ["/favicon_io/apple-touch-icon.png"],
    shortcut: ["/favicon_io/apple-touch-icon.png"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${specialGothic.variable}`} // ✅ apply font variable
    >
      <body>{children}</body>
    </html>
  );
}
